# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Grace Ruocco
tagline:             ''
description:         ''
url:                 https://gruocco.github.io
baseurl:             'https://gruocco.github.io'
plugins:
  - jekyll-paginate
paginate:            5

# About/contact
author:
  name:              Grace Ruocco
  url:               https://gruocco.github.io
  email:             ruoccoj19@gmail.com

# Custom vars
version:             1.0.0
